-----BEGIN RSA PRIVATE KEY-----
MIIEogIBAAKCAQEAwrHorf53NZcaGnJPl/VZN0/Edr59JnHz+s8yxwSCCjqUHm32
1jsbwNs+L4EvFLHdUjTgOIsgzFbk4ylFGWpuAyGuSSWxmssFvqyzo2W+tP6JuwIl
ekHVjJcftsrBtGofgb06i/PAS0NGWnmhCKAytMrl66UlHGayyCRNEV8xkeLryRod
zrlXLN8pXEEqhg/H6ZRDEWcMaYmEFMivI4O63X9gwLMZ8SZNT548k7ejnYBfYCFt
lKC1hzjV53f4F4EEijy9IHLUvSz99UkhlXVszsL55q7YAb8s5CbMuPDrmFdsSrSO
9CYYdVh1DTn3w3MLxfiXhdjqFectGtRmZxJoZQIDAQABAoIBABHxg5hFk4cE3gsB
7gP7QLWwTFMFS1N3vRyoa+2bpMB8lZoYWF92IyCrFBgct9IYcmVZKjEL4YHzoDSv
YQbuoCT5va5QIwY5H9Zq5ENy5RiZPOhXUkzqNFw4sVuPZDrUbQLwBa1QUbCeCqXb
/9NjsEipSndlSP5NGL0JW3D2bQMc1ZV3X24YurRM7wJOY8aMejRkSb0wKueYDRrb
RI4EFAQRP50/6RFo4fw9e+UAPRb6KcTBZNzkLU+dR8KZHL/OGthCqzdH6NNPlA0w
avsYsUrygiZRhRTFaJoE8Ov/OMr1WOA+bL9cahvSDMTPU7/GfKPtuocTs/4MSMwK
G3lngQECgYEA7LIlCVA680Ul8BJNUZyBqbkj4WERppJdrWHp1pefzpup7vn4AJk7
2q4HGE3D43t9GHhjXsdI2iNXp3Pf78ugWy/ddTd66tJx0UwhB0oEyDh79R6x7rGc
n6mA0WjBGs/zMaiMvvD8tgH74Y5nElqk+FkOBF2amYeGNJfC5MAEpmkCgYEA0pLZ
EYy6X0i2tcLF0JC1FFG7ZVslPtt0M3s/KuMBVgquS4ZTwMoZxipCXiY+QgfvlEJ6
2lGJm3vYDZEOZYCm6CaZdD713/KDQSRjxbdy1JTCkHG1ORFNDBEL6v97Oc2Oc1xW
DdFEyYTRMTZtfVohTPcoWf1Bk0eANuM98hNuSp0CgYBYAThyCQmSD8C2TSfAU0+G
elbT4pJ8e2knIQOfjQqW+BurxfcmydKOUSxEJg3SU8TER2azA6ebq45YrWWys+Qw
Y1CU14b1Lj+xUPvqyOOUSiQUlFAV7qXMW2qQ8cDypiTG7uM9zz42sfAkAh1inp89
02a5ys/Di7cjcNW+1YIlGQKBgGaNB9QpMjbnZbwdcFNDtjyAFYCmI/x5yhysYDYV
uffaWcoEUFOq2WSN/iZ1/4oO7VnKCqS6YwbrCGyLAXTjc+XJrqBTbVE0fUHDZCfN
UMpA7ISGLBjv2RMQVjqLU8rx1fdOt8Yg7Zwq5+pMtIQA2gjusaMp2L7Oap3Qi8GS
PvttAoGAIvrO5kvmm45KKTwWJ3KdPbp3NfJpsHPPQxQ0EfZ3vA4Cv5edSdgko2Or
as9ommsl5lgMkad1TbCCRZswrD7MVaPsmRmDMqCa9c1YXqbwmPjJfIc8G+Vodd2+
hwOinpq+jsRArisqK4lyIpRCJt1j2/9gNySghA7T7KOqbVPVPyY=
-----END RSA PRIVATE KEY-----
-----BEGIN CERTIFICATE-----
MIIDNTCCAh2gAwIBAgIUP/lumrzYvvhNWTUoBdZ3WSazAdAwDQYJKoZIhvcNAQEL
BQAwKDESMBAGA1UEAwwJbWl0bXByb3h5MRIwEAYDVQQKDAltaXRtcHJveHkwHhcN
MjUwNzE1MDA0NTA0WhcNMzUwNzE1MDA0NTA0WjAoMRIwEAYDVQQDDAltaXRtcHJv
eHkxEjAQBgNVBAoMCW1pdG1wcm94eTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
AQoCggEBAMKx6K3+dzWXGhpyT5f1WTdPxHa+fSZx8/rPMscEggo6lB5t9tY7G8Db
Pi+BLxSx3VI04DiLIMxW5OMpRRlqbgMhrkklsZrLBb6ss6NlvrT+ibsCJXpB1YyX
H7bKwbRqH4G9OovzwEtDRlp5oQigMrTK5eulJRxmssgkTRFfMZHi68kaHc65Vyzf
KVxBKoYPx+mUQxFnDGmJhBTIryODut1/YMCzGfEmTU+ePJO3o52AX2AhbZSgtYc4
1ed3+BeBBIo8vSBy1L0s/fVJIZV1bM7C+eau2AG/LOQmzLjw65hXbEq0jvQmGHVY
dQ0598NzC8X4l4XY6hXnLRrUZmcSaGUCAwEAAaNXMFUwDwYDVR0TAQH/BAUwAwEB
/zATBgNVHSUEDDAKBggrBgEFBQcDATAOBgNVHQ8BAf8EBAMCAQYwHQYDVR0OBBYE
FBK0bZb/xQPZzP6CyqkkVFLBxmx6MA0GCSqGSIb3DQEBCwUAA4IBAQDBVAjbg0cF
/oUFi7gaTglkqHtzx+Aw/sUzOFrd/orPwwjHEK7poV+32uLxeL6da/sI7oCZMAxX
+SidumA+MIZZNN8TD2lJjjsZDErhFKrzJ8tW5wxdgO7hzicjtpSTIlmIJvXigGZd
9vb23XH+jed3JW1d2wMQlobdlMUAi9/dKPitPEYybiNCgE4silUzvT/VTTzUy+Lx
0RVxvZz6IqqZqYGaXQyN/iS+BDUQGZU54sv7qPWssAzIv7XtTYkcKZV/EEwTCzUS
bcF7Mke6hDD6AaEr/MJlsfmm9wVQ/UDunGr6L4XbWpHblsvFkygoem9Ly0kJ56Dk
YAoC28PeXDQh
-----END CERTIFICATE-----
